// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-pitchers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pitchers_default = defineTool({
  name: "list_pitchers",
  title: "List pitchers",
  description: "List pitchers visible to the signed-in Arm Stats user (scoped by team membership via RLS). Returns id, name, and team_id.",
  inputSchema: {
    team_id: z.string().uuid().optional().describe("Optional team UUID to filter by. Omit to list across all of the user's teams.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("pitchers").select("id, name, team_id").order("name", { ascending: true });
    if (team_id) q = q.eq("team_id", team_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { pitchers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-outings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_outings_default = defineTool2({
  name: "list_recent_outings",
  title: "List recent outings",
  description: "List recent pitching outings for the signed-in user (bullpens, games, practice, external). Returns date, pitcher, event type, pitch count, strikes, max velocity, notes.",
  inputSchema: {
    pitcher_name: z2.string().trim().optional().describe("Filter by pitcher name (case-insensitive contains)."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    since: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only include outings on/after this ISO date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pitcher_name, limit, since }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("outings").select(
      "id, date, pitcher_name, event_type, pitch_count, strikes, max_velocity, focus, notes, team_id"
    ).order("date", { ascending: false }).limit(limit ?? 20);
    if (pitcher_name) q = q.ilike("pitcher_name", `%${pitcher_name}%`);
    if (since) q = q.gte("date", since);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { outings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-teams.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_teams_default = defineTool3({
  name: "list_teams",
  title: "List teams",
  description: "List the teams the signed-in Arm Stats user belongs to. Returns id, name, and weekly pitch cap.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("teams").select("id, name, max_weekly_pitches").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { teams: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-outing.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_outing_default = defineTool4({
  name: "log_outing",
  title: "Log an outing",
  description: "Insert a pitching outing (bullpen, game, practice, or external) for a pitcher. Acts as the signed-in Arm Stats user; RLS enforces team membership.",
  inputSchema: {
    pitcher_id: z3.string().describe("The pitcher_id string on the pitchers row."),
    pitcher_name: z3.string().min(1).describe("The pitcher's display name."),
    team_id: z3.string().uuid().describe("Team UUID this outing belongs to."),
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Outing date (YYYY-MM-DD, local)."),
    event_type: z3.enum(["bullpen", "game", "practice", "external"]).describe("Kind of outing."),
    pitch_count: z3.number().int().min(0).max(500),
    strikes: z3.number().int().min(0).max(500).nullable().optional().describe("Strike count. Null if not tracked."),
    max_velocity: z3.number().int().min(0).max(120).nullable().optional(),
    focus: z3.string().max(500).optional().describe("Mechanical focus / cue."),
    notes: z3.string().max(2e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("outings").insert({
      pitcher_id: input.pitcher_id,
      pitcher_name: input.pitcher_name,
      team_id: input.team_id,
      user_id: ctx.getUserId(),
      date: input.date,
      event_type: input.event_type,
      pitch_count: input.pitch_count,
      strikes: input.strikes ?? null,
      max_velocity: input.max_velocity ?? null,
      focus: input.focus ?? null,
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged outing ${data.id}` }],
      structuredContent: { outing: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zhhqakxjywbipmeyvlum";
var mcp_default = defineMcp({
  name: "arm-stats-mcp",
  title: "Arm Stats",
  version: "0.1.0",
  instructions: "Tools for Arm Stats (Arm Care Tracker). Coaches can list their teams and pitchers, review recent outings, and log new bullpen/game/practice/external outings for a pitcher. All tools act as the signed-in Arm Stats user and respect team-based row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_teams_default, list_pitchers_default, list_recent_outings_default, log_outing_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
